### PR TITLE
add a don't ask to ask command

### PR DESCRIPTION
**Pull request by Ragnar-Oock**
the command output is a simple embed of [https://dontasktoask.com](https://dontasktoask.com)
command aliases are "data" and "dontask"

### CODE REVIEW

**Review by talescript — COMMENTED** [review]
I like the pull request but I would add a description / explanation about it instead of sending the user somewhere else to read about it. If the user wants to read more then they can click on the link. Always think about the user experience (UX).

Questions:
- what does the data alias refer to?
- why is the function called conquering_layouts?

**Comment by Ragnar-Oock** [comment]
- what does the data alias refer to?
it's an acronym for "Don't Ask To Ask"
- why is the function called conquering_layouts?
I thought I had changed the name while copy-pasting it, but it seems like I forgot, I'll fix that.

for the explanation message I'll need to come up with something, it's indeed not really friendly to be sent a link like that xD

**Comment by talescript** [comment]
Nice. But I'm not sure since when I read data I'm thinking about information... but that might just be me.

**Comment by Ragnar-Oock** [comment]
"data" might indeed be a bit misleading, maybe having "dontask" is enough. A more verbose version like "dontasktoask" or "dont-ask-to-ask" might be interesting too

**Comment by Ragnar-Oock** [comment]
as for the explanation message, does this sound good to you?
> Help people help you. Don't ask to ask, just ask.
> Read more about this here
> \<embed goes here\>

**Comment by talescript** [comment]
Even Jerry Maguire gave a longer explanation 😄

https://youtu.be/l1B1_jQnlFk

Now I'm tempted to add a link to that video clip 😅... or maybe just make a new function called .rod / Jerry for that.

**Comment by Ragnar-Oock** [comment]
> Even Jerry Maguire gave a longer explanation

I'm not fond of lengthy explanations, even less when someone else did it before me in a way that's better I could ever do it xD

**Comment by talescript** [comment]
Added some inline comments to the code, not sure if you get notified about those. 

One is a type and the other is a suggestion for the description

Typo: should it be "enquiring"

Description: Be a good netizen and don't ask to ask. It wastes the other person's time by having to ask you what is the question and waiting for a reply. 

Rather ask "How do I do [problem] with Java and [other relevant info]?"

Instead of "click her to" read more I would suggest either:

* read more
* Learn more
* Learn more for free

**Comment by Ragnar-Oock** [comment]
phrasing and presentation suggestion for the message :

> Be a good netizen and don't ask to ask.
> It wastes the other person's time by having to ask you what is the question and waiting for a reply. Rather ask "How do I do [your problem] with Java and [other relevant info]?"
> 
> Learn more about why, for free, at the link below
> `embed goes here`

'bout the comments in the code, I don't know where you did them, but I haven't been notified.

**Pull request merged**
